In [ ]:
marks = [45, 60, 72, 38, 90]

total = 0

for i in range(len(marks) ):
    total += marks[i]

average = total / len(marks)

if average > 50:
    print("Class passed")
else:
    print("Class failed")
print(average)

Class passed
61.0


In [ ]:
subjects = ["Python", "Math", "AI", "Data"]

print(subjects)





print(subjects[0])


college={
    "name":"Mangesh Kumar",
    "college_name":"GLA UNIVERSITY",
    "section":"CA",
    "grades":'A+',
    "city":"Mathura"
}

info={
    "name":"krish",
    "college_name":"GLA UNIVERSITY",
    "section":"CC",
    "grades":"A+",
    "city":"Mathura"
}
info={
    "name":"Parth",
    "college_name":"GLA UNIVERSITY",
    "section":"CB",
    "grades":"A+",
    "city": "Mathura"
}

['Python', 'Math', 'AI', 'Data']
Python


In [ ]:
marks = 72

if marks<40 :
  print("fail")
elif marks>=40 and marks<=100 :
  print("pass")


pass


In [ ]:
students = [
    {"name": "Raju", "age": 20, "marks": 85},
    {"name": "Rahul", "age": 21, "marks": 72},
    {"name": "Chaman", "age": 19, "marks": 95},
    {"name": "Pawan", "age": 22, "marks": 88},
    {"name":"soham",  "age":24,  "marks":78}]

for i in students :
  if i.get("marks") > 70 :
    print(i.get("name"))
    print(i.get("marks"))

Raju
85
Rahul
72
Chaman
95
Pawan
88
soham
78


In [ ]:
def result(marks):
  if marks <40 :
    print("fail")
  else :
    print("pass")





In [ ]:

import numpy as np


marks = np.array([1,2,3,4,5])
print(marks.shape )

matrix = np.array([[10,20,30],[40,50,60]])

print(matrix)
print(matrix.shape)

(5,)
[[10 20 30]
 [40 50 60]]
(2, 3)


In [ ]:
marks = np.array([78,91,55,72,40,88])
reshape = marks.reshape(2,3)
print(reshape)

[[78 91 55]
 [72 40 88]]


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv.xls


In [ ]:
import pandas as pd

df = pd.read_csv("/content/session4_dummy_students_data.csv.xls")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [ ]:
sci= df['science'].to_numpy()
math = df['math'].to_numpy()
english = df['english'].to_numpy()
df['average'] = (sci + math + english )/3

In [ ]:
filter_1 = df[df['average']>85]
filter_2 = df[df['attendance_percent'] < 75 ]
filter_3 = df[df['city']=='Mathura']
print(filter_1)
print(filter_2)
print(filter_3)

    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score    average  
1                    93  91.000000  
5                    95  90.333333  
7                    91  92.000000  
13                   92  88.666667  
15             

In [ ]:
for i in df['average']:
  if i >=40:
    df['result'] = 'Pass'
  else :
    df['result'] = 'Fail'
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [ ]:
print(df['average'])
print(df['average'].max())
print(df['average'].min())
print(df[df['average']>=90]['name'])
print(df[df['attendance_percent']<75]['name'])
print(df[df['assignments_submitted']<6]['name'])


0     77.000000
1     91.000000
2     58.000000
3     77.333333
4     46.333333
5     90.333333
6     66.666667
7     92.000000
8     52.000000
9     81.333333
10    67.333333
11    78.000000
12    40.666667
13    88.666667
14    57.333333
15    92.666667
16    65.000000
17    82.666667
18    46.000000
19    76.666667
Name: average, dtype: float64
92.66666666666667
40.666666666666664
1       Diya
5       Sara
7     Ananya
15      Riya
Name: name, dtype: object
4      Rohan
8     Vivaan
12       Dev
18      Yash
Name: name, dtype: object
4     Rohan
12      Dev
18     Yash
Name: name, dtype: object


In [ ]:
print(df['final_project_score'].mean())
print(df[df['study_hours_per_week']>8]['name'])
mumbai = df[df['city']=='Mumbai']['average'].mean()
pune = df[df['city']=='Pune']['average'].mean()
if mumbai > pune :
  print('Mumbai > Pune')
elif mumbai == pune :
  print('Mumbai = Pune')
else  :
  print('Mumbai < Pune')


73.65
1       Diya
5       Sara
7     Ananya
9       Tara
13     Priya
15      Riya
17     Aditi
Name: name, dtype: object
Mumbai < Pune
